# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
  - format: colored-line-number
    path: stdout
  - format: html
    path: tmp/linter-report-backend.html

linters:
  disable-all: true
  enable:
    - errcheck
    - gocognit
    - goconst
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nlreturn
    - perfsprint
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unused

linters-settings:
  govet:
    enable-all: true
    disable:
      # There is rarely performance differences due to padding,
      # the most noticable impact is memory usage. However,
      # the main trace data is Protobuf-generated and we ignore
      # those files from linting, so this linter is not useful.
      - fieldalignment
      # Disable shadow
      - printf
      - shadow
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2
  lll:
    line-length: 120
  perfsprint:
    # Optimizes even if it requires an int or uint type cast.
    int-conversion: true
    # Optimizes into `err.Error()` even if it is only equivalent for non-nil errors.
    err-error: true
    # Optimizes `fmt.Errorf`.
    errorf: true
    # Optimizes `fmt.Sprintf` with only one argument.
    sprintf1: true
    # Optimizes into strings concatenation.
    strconcat: true
  nlreturn:
    # Size of the block (including return statement that is still "OK")
    # so no return split required.
    # Default: 1
    block-size: 5

issues:
  exclude-use-default: false
  exclude:
    # _ instead of err checks
    - G104
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - mocks
    - \.cache
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
