version: '3'

includes:
  build: ./taskfiles/build.yml
  deps: ./taskfiles/deps.yml
  dev: 
    taskfile: ./taskfiles/dev.yml
    flatten: true
  test: ./taskfiles/test.yml

tasks:
  default:
    cmds:
      - task --list
